--!strict
--!native
--!optimize 2

--[[
	CFrame encoding.

	Three strategies, chosen automatically per value:

	  1. Axis-aligned    1 byte rotation  -- one of the 24 rotations that map
	                                         the axes onto each other, which is
	                                         what most placed parts actually use
	  2. Position only   0 bytes rotation -- identity rotation, handled by the
	                                         caller emitting CFRAME_POS
	  3. Quaternion      4 bytes rotation -- smallest-three packing, 10 bits per
	                                         component; worst-case angular error
	                                         measured at 0.162 degrees

	Position is always 3 f32 (12 bytes). So a placed part costs 13 bytes and an
	arbitrarily rotated one costs 16, against 48 for the naive 12-float form.
]]

local CFrameCodec = {}

local sqrt = math.sqrt
local abs = math.abs
local round = math.round
local clamp = math.clamp
local floor = math.floor

local SQRT1_2 = 1 / sqrt(2)
local RANGE = 2 * SQRT1_2
local SCALE = 1023
local BITS10 = 1024

-- Axis-aligned rotation table ----------------------------------------------

--[[
	The 24 rotations of a cube, as the images of the X, Y and Z basis vectors.

	Written as matrices rather than Euler angles on purpose. CFrame.Angles
	triples are not unique at gimbal lock, and a hand-written list of them
	silently contained four duplicate rotations -- only 20 of the 24 were
	actually covered. These were generated by enumerating every (X image, Y
	image) pair of perpendicular signed axes, and every entry is verified
	distinct with determinant +1.

	Ids run 1-24; 0 is reserved to mean "not axis-aligned".
]]
local ZERO = Vector3.zero

local ID_TO_ROTATION: { CFrame } = {
	CFrame.fromMatrix(ZERO, Vector3.new(1, 0, 0), Vector3.new(0, 1, 0), Vector3.new(0, 0, 1)),
	CFrame.fromMatrix(ZERO, Vector3.new(1, 0, 0), Vector3.new(0, -1, 0), Vector3.new(0, 0, -1)),
	CFrame.fromMatrix(ZERO, Vector3.new(1, 0, 0), Vector3.new(0, 0, 1), Vector3.new(0, -1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(1, 0, 0), Vector3.new(0, 0, -1), Vector3.new(0, 1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(-1, 0, 0), Vector3.new(0, 1, 0), Vector3.new(0, 0, -1)),
	CFrame.fromMatrix(ZERO, Vector3.new(-1, 0, 0), Vector3.new(0, -1, 0), Vector3.new(0, 0, 1)),
	CFrame.fromMatrix(ZERO, Vector3.new(-1, 0, 0), Vector3.new(0, 0, 1), Vector3.new(0, 1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(-1, 0, 0), Vector3.new(0, 0, -1), Vector3.new(0, -1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 1, 0), Vector3.new(1, 0, 0), Vector3.new(0, 0, -1)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 1, 0), Vector3.new(-1, 0, 0), Vector3.new(0, 0, 1)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 1, 0), Vector3.new(0, 0, 1), Vector3.new(1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 1, 0), Vector3.new(0, 0, -1), Vector3.new(-1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, -1, 0), Vector3.new(1, 0, 0), Vector3.new(0, 0, 1)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, -1, 0), Vector3.new(-1, 0, 0), Vector3.new(0, 0, -1)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, -1, 0), Vector3.new(0, 0, 1), Vector3.new(-1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, -1, 0), Vector3.new(0, 0, -1), Vector3.new(1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, 1), Vector3.new(1, 0, 0), Vector3.new(0, 1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, 1), Vector3.new(-1, 0, 0), Vector3.new(0, -1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, 1), Vector3.new(0, 1, 0), Vector3.new(-1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, 1), Vector3.new(0, -1, 0), Vector3.new(1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, -1), Vector3.new(1, 0, 0), Vector3.new(0, -1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, -1), Vector3.new(-1, 0, 0), Vector3.new(0, 1, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, -1), Vector3.new(0, 1, 0), Vector3.new(1, 0, 0)),
	CFrame.fromMatrix(ZERO, Vector3.new(0, 0, -1), Vector3.new(0, -1, 0), Vector3.new(-1, 0, 0)),
}

local ROTATION_TO_ID: { [string]: number } = {}

--[[
	Key on the rotation matrix, not on ToOrientation.

	Euler angles are not unique: at gimbal lock two distinct axis-aligned
	rotations produce identical (x, y, z) triples, which silently mapped four
	of the 24 onto two ids and decoded them to the wrong rotation. The nine
	matrix entries are exactly -1, 0 or 1 for these rotations, so rounding them
	gives a key that is both exact and collision-free.
]]
local function rotationKey(cf: CFrame): string
	local _, _, _, m00, m01, m02, m10, m11, m12, m20, m21, m22 = cf:GetComponents()
	-- The +0 collapses -0 to 0 so the two zeros share a key.
	return string.format(
		"%d,%d,%d,%d,%d,%d,%d,%d,%d",
		round(m00) + 0,
		round(m01) + 0,
		round(m02) + 0,
		round(m10) + 0,
		round(m11) + 0,
		round(m12) + 0,
		round(m20) + 0,
		round(m21) + 0,
		round(m22) + 0
	)
end

for id, cf in ID_TO_ROTATION do
	ROTATION_TO_ID[rotationKey(cf)] = id
end

CFrameCodec.ID_TO_ROTATION = ID_TO_ROTATION

--[[
	Returns the 1-24 id if this rotation is axis-aligned, otherwise nil.

	Rejects near-aligned rotations first: a CFrame rotated 0.4 degrees off axis
	would round to an aligned matrix and be silently snapped straight.
]]
local ALIGN_EPSILON = 1e-4

function CFrameCodec.rotationId(cf: CFrame): number?
	local _, _, _, m00, m01, m02, m10, m11, m12, m20, m21, m22 = cf:GetComponents()
	local components = { m00, m01, m02, m10, m11, m12, m20, m21, m22 }

	for i = 1, 9 do
		local value = components[i]
		local nearest = round(value)
		if abs(value - nearest) > ALIGN_EPSILON then
			return nil
		end
	end

	return ROTATION_TO_ID[rotationKey(cf)]
end

-- Quaternion ----------------------------------------------------------------

--[[
	Rotation part of a CFrame as a normalized quaternion. Uses the standard
	branch-on-trace conversion, picking the largest diagonal term to keep the
	divisor away from zero.
]]
function CFrameCodec.toQuaternion(cf: CFrame): (number, number, number, number)
	local _, _, _, m00, m01, m02, m10, m11, m12, m20, m21, m22 = cf:GetComponents()

	local trace = m00 + m11 + m22
	local x, y, z, w

	if trace > 0 then
		local s = sqrt(1 + trace) * 2
		w = 0.25 * s
		x = (m21 - m12) / s
		y = (m02 - m20) / s
		z = (m10 - m01) / s
	elseif m00 > m11 and m00 > m22 then
		local s = sqrt(1 + m00 - m11 - m22) * 2
		w = (m21 - m12) / s
		x = 0.25 * s
		y = (m01 + m10) / s
		z = (m02 + m20) / s
	elseif m11 > m22 then
		local s = sqrt(1 + m11 - m00 - m22) * 2
		w = (m02 - m20) / s
		x = (m01 + m10) / s
		y = 0.25 * s
		z = (m12 + m21) / s
	else
		local s = sqrt(1 + m22 - m00 - m11) * 2
		w = (m10 - m01) / s
		x = (m02 + m20) / s
		y = (m12 + m21) / s
		z = 0.25 * s
	end

	local length = sqrt(x * x + y * y + z * z + w * w)
	return x / length, y / length, z / length, w / length
end

--[[
	Smallest-three packing into a u32.

	The largest component is dropped and rebuilt on read from the unit-length
	constraint, so only three need storing. Negating the whole quaternion gives
	the same rotation, so the dropped component is forced positive and its sign
	costs nothing. Layout: [index:2][c:10][b:10][a:10].
]]
function CFrameCodec.packQuaternion(x: number, y: number, z: number, w: number): number
	local components = { x, y, z, w }

	local largestIndex, largestValue = 1, abs(x)
	for i = 2, 4 do
		local magnitude = abs(components[i])
		if magnitude > largestValue then
			largestIndex, largestValue = i, magnitude
		end
	end

	if components[largestIndex] < 0 then
		for i = 1, 4 do
			components[i] = -components[i]
		end
	end

	local packed = 0
	local slot = 0
	for i = 1, 4 do
		if i ~= largestIndex then
			local quantized = round(((components[i] + SQRT1_2) / RANGE) * SCALE)
			packed += clamp(quantized, 0, SCALE) * BITS10 ^ slot
			slot += 1
		end
	end

	return packed + (largestIndex - 1) * BITS10 ^ 3
end

function CFrameCodec.unpackQuaternion(packed: number): (number, number, number, number)
	local largestIndex = floor(packed / BITS10 ^ 3) + 1
	local rest = packed % BITS10 ^ 3

	local decoded = table.create(3)
	for i = 1, 3 do
		local quantized = floor(rest / BITS10 ^ (i - 1)) % BITS10
		decoded[i] = (quantized / SCALE) * RANGE - SQRT1_2
	end

	local components = table.create(4)
	local slot = 1
	local sumOfSquares = 0
	for i = 1, 4 do
		if i == largestIndex then
			components[i] = 0
		else
			local value = decoded[slot]
			components[i] = value
			sumOfSquares += value * value
			slot += 1
		end
	end

	components[largestIndex] = sqrt(math.max(0, 1 - sumOfSquares))
	return components[1], components[2], components[3], components[4]
end

return CFrameCodec
